Mangopay/mangopay2-nodejs-sdk

lib/api.js

@hobailey I pushed a update to validate for 401 status code, and if so, renew the Authorization token and redo the request. Please let me know if there's any way I can simulate this behavior on the testing machines.
Thanks !

Fix expired authorization token error

---

docs/Mandates.md
docs/README.md
lib/Model.js
lib/apiMethods.js
lib/models/Mandate.js
lib/models/MandateStatus.js
lib/services/Mandates.js
package.json
test/services/Mandates.js

Implement mandates feature as described in the docs https://docs.mangopay.com/endpoints/v2.01/mandates

Mandates Feature

---

docs/README.md
docs/Reports.md
lib/apiMethods.js
lib/models/Report.js
lib/models/ReportFilter.js
lib/services/Reports.js
test/services/Reports.js

Reports feature

---

examples/failedRequest.js
lib/api.js
test/helpers.js
test/services/CardPreAuthorizations.js
test/services/CardRegistrations.js
test/services/Events.js
test/services/Hooks.js
test/services/KycDocuments.js
test/services/Mandates.js
test/services/PayIns.js
test/services/PayOuts.js
test/services/Refunds.js
test/services/Transfers.js
test/services/Users.js
test/services/Wallets.js

API requests that fail will reject the promise

#32 Promises not rejected when server error occurs

---

lib/api.js
test/services/CardRegistrations.js

Add fix for #45 and test for regression check

Enahance promise rejection

---

lib/api.js
test/services/Tokens.js

Fix authorization failure issue

---

lib/services/PayIns.js

Fix payment details method

---

lib/apiMethods.js
lib/models/PayInPaymentDetailsPayPal.js
lib/models/PayInPaymentType.js
lib/models/ShippingAddress.js
lib/services/PayIns.js
test/services/PayIns.js

Complete with the ShippingAddress property and class.

Added support for the PayPal PayIn type.

---

lib/services/BankingAliases.js
test/services/CardRegistrations.js

Removed useless console log calls.

Fixed documentation typo.

---

lib/models/DisputeDocument.js
lib/models/Document.js
lib/models/KycDocument.js

Added Document base entity to hold properties common to the KYC and dispute document entities.

Added ProcessedDate property.

---

lib/apiMethods.js
lib/models/DeclaredUbo.js
lib/models/DeclaredUboStatus.js
lib/models/UboDeclaration.js
lib/models/UboDeclarationRefusedReasonType.js
lib/models/UboDeclarationStatus.js
lib/models/UboRefusedReasonType.js
lib/models/UserNatural.js
lib/models/UserNaturalCapacity.js
lib/services/UboDeclarations.js
lib/services/Users.js
test/helpers.js
test/services/UboDeclarations.js
test/services/Users.js

Sorry about the incorrect commit message.

Added support for UBO declarations.

---

docs/BankingAliases.md
docs/Cards.md
docs/DisputeDocuments.md
docs/KycDocuments.md
docs/README.md
docs/UboDeclarations.md
docs/Users.md
lib/services/Users.js

I just want to fix the docs:
`Users.updateKycDocument(userId, kycDocumentId, callback, options) `
should be 
`Users.updateKycDocument(userId, kycDocument, callback, options) `
and `kycDocument` is an object

User.updateKycDocument() fix doc

---

test/services/Events.js
test/services/Users.js

Fixed a test failing due to incorrect checking of dates.

Temporary fix for the failing Events test.

---

lib/apiMethods.js
lib/services/Repudiations.js
test/services/Repudiations.js

Implemented Get Refunds for a Repudiation.

---

README.md
lib/api.js
test/helpers.js
test/services/BankingAliases.js
test/services/CardRegistrations.js
test/services/Clients.js
test/services/KycDocuments.js
test/services/Mandates.js
test/services/Reports.js
test/services/Users.js
test/services/Wallets.js

Cleaned up proimse callbacks (response param was never used)

---

examples/createUsers.js
examples/createWallet.js

The first example was displaying `undefined` because `CreationDate` is not defined in the file, but yet exists in the returned object. To fix that, I added a parameter (`myReturnedUser`) to the anonymous function. 
I also added 2 examples:
- creating a natural user with only required values
- failing at creating a natural user to show how to catch an error

fix 'undefined' value and add more examples

---

lib/apiMethods.js
lib/models/Address.js
lib/models/Birthplace.js
lib/models/Ubo.js
lib/models/UboDeclaration.js
lib/models/UboDeclarationRefusedReasonType.js
lib/models/UboDeclarationStatus.js
lib/services/UboDeclarations.js
lib/services/Users.js
test/helpers.js
test/services/UboDeclarations.js

#143
added support for New UBO submission system support

New UBO submission system support

---

.jshintrc
examples/getUserEmoney.js
lib/apiMethods.js
lib/services/Users.js
test/main.js
test/services/CardPreAuthorizations.js
test/services/EMoney.js
test/services/PayIns.js

Support for users emoney multiperiod

---

lib/apiMethods.js
lib/models/PayInPaymentDetailsApplePay.js
lib/models/PayInPaymentType.js
lib/models/PaymentData.js
lib/services/PayIns.js
test/services/PayIns.js

Added support for ApplePay Payins

---

lib/api.js
lib/services/Clients.js
lib/services/Disputes.js
lib/services/Users.js
test/helpers.js
test/services/CardRegistrations.js

modified all instances of deprecated 'new Buffer()' constructor used in the API

Changed deprecated 'new Buffer()' constructor

---

lib/api.js
package.json

updated 'node-rest-client' dependency to the last version (v3.1.0)

'node-rest-client' dependency version update

---

.travis.yml
lib/services/BankAccounts.js
lib/services/Cards.js
lib/services/Clients.js
lib/services/DisputeDocuments.js
lib/services/Disputes.js
lib/services/Events.js
lib/services/Hooks.js
lib/services/KycDocuments.js
lib/services/Mandates.js
lib/services/PayIns.js
lib/services/PayOuts.js
lib/services/Repudiations.js
lib/services/Transfers.js
lib/services/UboDeclarations.js
lib/services/Users.js
lib/services/Wallets.js
test/services/Hooks.js
test/services/Wallets.js

This should solve both #137 and #135 issues.
I also updated the travis node version. The old one was not working with the 'spread' operator.

135 fix pagination wallets get transactions

---

lib/models/UserNaturalPut.js
lib/services/Users.js
test/services/Users.js

[fixes this](https://github.com/Mangopay/mangopay2-nodejs-sdk/issues/224)

few changed to the update mechanism to match other sdks

---

typings/index.d.ts

[fixes this](https://github.com/Mangopay/mangopay2-nodejs-sdk/issues/230)

added typing info

---

typings/index.d.ts

[](https://github.com/Mangopay/mangopay2-nodejs-sdk/issues/249)

Added BrowserInfo for CreateCardDirectPayIn

---

typings/index.d.ts

Fixed issue 252

---

typings/index.d.ts

Quick wording error, changing ScreehWidth into ScreenWidth

bugfix ScreehWidth Wording

---

lib/models/UboDeclarationRefusedReasonType.js
typings/enums.d.ts
typings/mangopay2-nodejs-sdk-tests.ts
typings/models/uboDeclaration.d.ts

- added missing uboId to the 'UpdateUbo' object; 
- updated UboDeclarationRefusedReasonType with the latest values; 
- added missing types to the UboDeclarationData object

Bugfix: missing UpdateUbo ID

---

lib/models/Refund.js
test/helpers.js
typings/mangopay2-nodejs-sdk-tests.ts
typings/models/payIn.d.ts

@iulian03 please check this one carefully

improvement/Added reference to the new PayPal implementation

---

lib/services/Users.js

Fix comment on get bank account

fixed comment on getBankAccount

---

.github/workflows/node.js.yml

run tests only on PR and push on master

Improvement on Github actions

---

typings/models/card.d.ts

Add missing UserId to CardData type

---

lib/apiMethods.js
lib/models/PayInPaymentDetailsBancontact.js
lib/models/PayInPaymentType.js
lib/models/index.js
lib/services/PayIns.js
test/helpers.js
test/services/PayIns.js
typings/enums.d.ts
typings/models/card.d.ts
typings/models/cardPreauthorization.d.ts
typings/models/cardValidation.d.ts
typings/models/payIn.d.ts
typings/models/refund.d.ts
typings/services/PayIns.d.ts
typings/types.d.ts

- "StatementDescriptor" to "create/view PayIn Refund"
- "PaymentCategory" to "create card validation", "create card payin", "create preauthorization"
- "CardHolderName" to "update card"

added new params

---

package.json

version bump axios

---

typings/models/event.d.ts

Adds VIRTUAL_ACCOUNT_ACTIVE, VIRTUAL_ACCOUNT_BLOCKED, VIRTUAL_ACCOUNT_CLOSED, VIRTUAL_ACCOUNT_FAILED in EVENT_TYPE_CHOICES

Add EventTypes for Virtual Accounts

---

lib/apiMethods.js
lib/models/PayInRecurringRegistration.js
lib/services/PayIns.js
test/services/PayIns.js
typings/index.d.ts
typings/models/payIn.d.ts
typings/services/PayIns.d.ts
typings/types.d.ts

[feature] recurring paypal payin

---

lib/services/Wallets.js
test/services/Users.js
test/services/Wallets.js

added tests for extracting PendingUserAction RedirectUrl in case of 401 ScaContext

[feature] sca context on GET endpoints

---

lib/models/VirtualAccount.js
typings/index.d.ts
typings/models/virtualAccount.d.ts

Reverts Mangopay/mangopay2-nodejs-sdk#469

Revert "[feature] handle virtual account updates"
